# -*- coding: utf-8 -*-
"""Sistema de Gestión de Inventarios

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17kXUP34tqdqYTq7LFHf1kPGCBmctNZOx
"""

# Definición de la clase Producto
# Esta clase representa un producto individual en el inventario.
# Encapsula las propiedades de un producto y proporciona métodos para acceder y modificarlas.
class Producto:
    # Constructor de la clase Producto
    # Inicializa un nuevo objeto Producto con un ID único, nombre, cantidad y precio.
    # Se utiliza un guion bajo '_' para indicar que los atributos son 'protegidos' (convención de Python).
    def __init__(self, ID, nombre, cantidad, precio):
        self._ID = ID
        self._nombre = nombre
        self._cantidad = cantidad
        self._precio = precio

    # Métodos Getter: Permiten acceder a los valores de los atributos del producto.
    def get_ID(self):
        return self._ID

    def get_nombre(self):
        return self._nombre

    def get_cantidad(self):
        return self._cantidad

    def get_precio(self):
        return self._precio

    # Métodos Setter: Permiten modificar los valores de los atributos del producto.
    # Son útiles para actualizar la información de un producto después de su creación.
    def set_ID(self, new_ID):
        self._ID = new_ID

    def set_nombre(self, new_nombre):
        self._nombre = new_nombre

    def set_cantidad(self, new_cantidad):
        self._cantidad = new_cantidad

    def set_precio(self, new_precio):
        self._precio = new_precio

print("Clase 'Producto' definida correctamente.")
# Definición de la clase Inventario
# Esta clase gestiona una colección de objetos Producto.
# Proporciona funcionalidades para añadir, eliminar, actualizar, buscar y mostrar productos.
class Inventario:
    # Constructor de la clase Inventario
    # Inicializa el inventario con una lista vacía para almacenar los productos.
    def __init__(self):
        self._productos = []
        print("Inventario inicializado con una lista de productos vacía.")

    # Método para añadir un producto al inventario.
    # Verifica que el ID del producto sea único antes de añadirlo.
    def añadir_producto(self, producto):
        for p in self._productos:
            if p.get_ID() == producto.get_ID():
                print(f"Error: Producto con ID {producto.get_ID()} ya existe. El ID debe ser único.")
                return # Sale de la función si el ID ya existe
        self._productos.append(producto)
        print(f"Producto '{producto.get_nombre()}' con ID {producto.get_ID()} añadido al inventario.")

    # Método para eliminar un producto del inventario por su ID.
    # Itera sobre la lista de productos para encontrar y eliminar el que coincida con el ID proporcionado.
    def eliminar_producto(self, id):
        producto_encontrado = None
        for p in self._productos:
            if p.get_ID() == id:
                producto_encontrado = p
                break # Sale del bucle una vez que se encuentra el producto

        if producto_encontrado:
            self._productos.remove(producto_encontrado)
            print(f"Producto con ID {id} eliminado del inventario.")
        else:
            print(f"Error: Producto con ID {id} no encontrado.")

    # Método para actualizar la cantidad o el precio de un producto por su ID.
    # Permite actualizar uno o ambos atributos (cantidad y precio).
    def actualizar_producto(self, id, nueva_cantidad=None, nuevo_precio=None):
        producto_encontrado = None
        for p in self._productos:
            if p.get_ID() == id:
                producto_encontrado = p
                break

        if producto_encontrado:
            actualizado = False # Bandera para verificar si se realizó alguna actualización
            if nueva_cantidad is not None:
                producto_encontrado.set_cantidad(nueva_cantidad)
                print(f"Cantidad del producto ID {id} actualizada a {nueva_cantidad}.")
                actualizado = True
            if nuevo_precio is not None:
                producto_encontrado.set_precio(nuevo_precio)
                print(f"Precio del producto ID {id} actualizado a {nuevo_precio}.")
                actualizado = True
            if not actualizado:
                print(f"No se proporcionaron nuevos datos para actualizar el producto ID {id}.")
        else:
            print(f"Error: Producto con ID {id} no encontrado.")

    # Método para buscar productos por nombre (búsqueda parcial y sin distinción de mayúsculas/minúsculas).
    # Retorna una lista de productos que coinciden con el nombre de búsqueda.
    def buscar_producto_por_nombre(self, nombre):
        productos_coincidentes = []
        nombre_lower = nombre.lower() # Convierte el nombre de búsqueda a minúsculas para una comparación flexible
        for p in self._productos:
            if nombre_lower in p.get_nombre().lower(): # Compara el nombre del producto (en minúsculas) con el nombre de búsqueda
                productos_coincidentes.append(p)
        return productos_coincidentes

    # Método para mostrar todos los productos actualmente en el inventario.
    # Imprime los detalles de cada producto o un mensaje si el inventario está vacío.
    def mostrar_productos(self):
        if not self._productos:
            print("El inventario está vacío.")
        else:
            print("\n--- Productos en Inventario ---")
            for p in self._productos:
                print(f"ID: {p.get_ID()}, Nombre: {p.get_nombre()}, Cantidad: {p.get_cantidad()}, Precio: {p.get_precio():.2f}")
            print("-------------------------------")

print("Clase 'Inventario' definida correctamente.")
# Función para mostrar el menú de opciones al usuario
def mostrar_menu():
    print("\n--- Menú de Gestión de Inventario ---")
    print("1. Añadir nuevo producto")
    print("2. Eliminar producto")
    print(
        "3. Actualizar cantidad o precio de producto"
    )
    print("4. Buscar producto por nombre")
    print("5. Mostrar todos los productos")
    print("6. Salir")
    print("-------------------------------------")

# Función principal que ejecuta la aplicación de gestión de inventario
def main():
    # Crea una instancia de la clase Inventario al inicio de la aplicación
    inventario = Inventario()

    # Bucle principal de la aplicación: se ejecuta continuamente hasta que el usuario elija salir
    while True:
        mostrar_menu() # Muestra las opciones del menú
        opcion = input("Seleccione una opción: ") # Solicita al usuario que elija una opción

        # Bloque condicional para manejar las diferentes opciones del menú
        if opcion == '1':
            # Opción 1: Añadir nuevo producto
            try:
                producto_id = input("Ingrese el ID del producto: ")
                nombre = input("Ingrese el nombre del producto: ")
                cantidad = int(input("Ingrese la cantidad: ")) # Convierte la entrada a entero
                precio = float(input("Ingrese el precio: ")) # Convierte la entrada a flotante

                # Validación básica: la cantidad y el precio no pueden ser negativos
                if cantidad < 0 or precio < 0:
                    print(
                        "Error: La cantidad y el precio no pueden ser negativos."
                    )
                    continue # Vuelve a mostrar el menú si hay un error

                # Crea un nuevo objeto Producto y lo añade al inventario
                nuevo_producto = Producto(
                    producto_id, nombre, cantidad, precio
                )
                inventario.añadir_producto(nuevo_producto)
            except ValueError:
                # Captura errores si la cantidad o el precio no son números válidos
                print("Error: Cantidad y precio deben ser números válidos.")

        elif opcion == '2':
            # Opción 2: Eliminar producto
            producto_id = input(
                "Ingrese el ID del producto a eliminar: "
            )
            inventario.eliminar_producto(producto_id)

        elif opcion == '3':
            # Opción 3: Actualizar cantidad o precio de producto
            producto_id = input(
                "Ingrese el ID del producto a actualizar: "
            )
            # Se permite dejar las entradas en blanco si no se desea actualizar un campo específico
            nueva_cantidad_str = input(
                "Ingrese nueva cantidad (deje en blanco para no actualizar): "
            )
            nuevo_precio_str = input(
                "Ingrese nuevo precio (deje en blanco para no actualizar): "
            )

            nueva_cantidad = None
            nuevo_precio = None

            try:
                # Intenta convertir las entradas a números si no están vacías
                if nueva_cantidad_str:
                    nueva_cantidad = int(nueva_cantidad_str)
                    if nueva_cantidad < 0:
                        print("Error: La cantidad no puede ser negativa.")
                        continue
                if nuevo_precio_str:
                    nuevo_precio = float(nuevo_precio_str)
                    if nuevo_precio < 0:
                        print("Error: El precio no puede ser negativo.")
                        continue
            except ValueError:
                print(
                    "Error: Cantidad o precio deben ser números válidos."
                )
                continue

            # Llama al método de actualización solo si se proporcionó al menos un nuevo dato
            if nueva_cantidad is not None or nuevo_precio is not None:
                inventario.actualizar_producto(
                    producto_id, nueva_cantidad, nuevo_precio
                )
            else:
                print("No se proporcionaron datos para actualizar.")

        elif opcion == '4':
            # Opción 4: Buscar producto por nombre
            nombre_busqueda = input(
                "Ingrese el nombre o parte del nombre del producto a buscar: "
            )
            productos_encontrados = inventario.buscar_producto_por_nombre(
                nombre_busqueda
            )
            if productos_encontrados:
                print("\n--- Productos Encontrados ---")
                for p in productos_encontrados:
                    print(
                        f"ID: {p.get_ID()}, Nombre: {p.get_nombre()}, Cantidad: {p.get_cantidad()}, Precio: {p.get_precio():.2f}"
                    )
                print("-----------------------------")
            else:
                print(
                    f"No se encontraron productos con '{nombre_busqueda}'."
                )

        elif opcion == '5':
            # Opción 5: Mostrar todos los productos
            inventario.mostrar_productos()

        elif opcion == '6':
            # Opción 6: Salir de la aplicación
            print("Saliendo de la aplicación. ¡Hasta luego!")
            break # Rompe el bucle while y finaliza la aplicación

        else:
            # Manejo de opciones no válidas
            print("Opción no válida. Por favor, intente de nuevo.")


# Punto de entrada de la aplicación
# Este bloque asegura que main() se ejecute solo cuando el script es ejecutado directamente
# y no cuando es importado como un módulo.
if __name__ == '__main__':
    main()

print("Implementación de la Interfaz de Usuario en Consola añadida. Ejecute la función main() para iniciar la aplicación.")